### ISSUE TITLE
testportalantyspy - "zanihilowano szpiega"

### ISSUE THREAD

**Issue by ejakulacja** [skhyr/anihilator#10]
mam następujący problem z twoim rozszerzeniem do chroma. Kiedy skopiowałem link i strona z testem juz mi się odpaliła w na dole ekranu wyskoczył napis "zanihilowano szpiega". Czy to jest jakiś Bug i da się go naprawić czy wynika to z zabezpieczeń jakie nakłada strona na ten test? Prosze o szybką odpowiedź ;)

**Comment by skhyr** [comment]
To informacja od wtyczki że się uruchomiła i że nagle testportal nie odwalił maniany blokując tego, po prostu dodatkowy stopień pewności że jest ok. Jak Ci to bardzo przeszkadza to możesz wyłączyć to, najłatwiej w css display: none; na odpowiedniej klasie

**Comment by XdekHckr** [comment]
> To informacja od wtyczki że się uruchomiła i że nagle testportal nie odwalił maniany blokując tego, po prostu dodatkowy stopień pewności że jest ok. Jak Ci to bardzo przeszkadza to możesz wyłączyć to, najłatwiej w css display: none; na odpowiedniej klasie

typie w tym folderze po rozpakowaniu sa tylko 3 screeny i nie ma rozszerzenia

**Comment by skhyr** [comment]
@PanSmuggler  wybierz branch chrome najpierw :D i polecam czytać wszystko jest napisane w readme

**Comment by XdekHckr** [comment]
> @PanSmuggler wybierz branch chrome najpierw :D i polecam czytać wszystko jest napisane w readme

dobra ale mogles w jedym miejscu to dac bo ja slepy byłem

**Comment by skhyr** [comment]
@PanSmuggler  jest na osobnym branchu bo chciałem dać firefoxa jeszczse ale ostatecznie nie wyszło

**Comment by skhyr** [comment]
Dobra ez zostało uproszone troche nie ma już zabawy w branche
