### ISSUE TITLE
Cześć :)

### ISSUE THREAD

**Issue by 4rcz3r** [skhyr/anihilator#2]

**Comment by TheLogan117** [comment]
Mordo,
z tego co widzę musiałeś odezwać się do jednej konkretnej osoby ale maila o tym issue dostaną wszystkie skoro nie pasuje do mnie charakterystyka gościa o której mowa. Moje repo jest czyste a o JS wiem tyle co nic bo siedzę w wirtualkach a nie developmencie.

Skoro już mowa o _issues_ to powinieneś wiedzieć, że szpieg się nie anihiluje na pierwszej (powitalnej) i ostatniej (wynik) stronie testu. Tam prawdopodobnie nawet nie ma co anihilować bo szpieg działa tylko przy wyświetlaniu pytań podczas testu.

**Comment by 4rcz3r** [comment]
Szczerze? Nie wiem do kogo to trafia i jakoś mnie to zbytnio nie interesuje "Mordo" XD 
Chyba już nie razi w oczy.
To o anihilacji to chyba nie do mnie? wt* ...

**Comment by diel0** [comment]
Wow, dostałem maile i znalazłem się tutaj :D.

**Comment by skhyr** [comment]
Działało dobrze ale była aktualizacja i przestało. Przerabiając na szybko popełniłem błąd i teraz nie jest efektywne ale w weekend zrobię co trzeba i będzie git

**Comment by Xonn1com** [comment]
Napisane jest, że zainihilowano szpiega (czy coś w tym rodzaju), ale nie działa; dalej blokuje i wyświetla komunikat z ostrzeżeniem :(
