### ISSUE TITLE
Błąd dodatków w chrome

### ISSUE THREAD

**Issue by Dominikodz** [skhyr/anihilator#4]
Tak jak tytuł pisze, pokazuje błąd podczas wchodzenia na test. Nie wiem czy można jeszcze można to odratować, ale będę czekać.

Screen
https://i.imgur.com/IXMmkxD.png
![image](https://user-images.githubusercontent.com/64926921/82895168-11079400-9f54-11ea-9eff-c91bc0ccd0d6.png)

**Comment by skhyr** [comment]
@Xonn1com pracuje nad tym, raczej da się zrobić

**Comment by mikart143** [comment]
Czy są jakieś postępy ?

**Comment by skhyr** [comment]
@mikart143 tak ale niewystarczające do działania ;(

**Comment by skhyr** [comment]
no i nie umiem zostałem pokonany przez własne rady które im dałem F

**Comment by Michelel5000** [comment]
F

**Comment by Dominikodz** [comment]
**Jak napisze jakieś głupoty to przepraszam**, dopiero się uczę programować cpp. Jak testportal blokuje wtyczkę to można jakoś ją ukryć?Albo usunąć od razu tego EventListenera co dodaje hasFocus i wtedy wejść na strone (dopóki jest EventListener to strona nie ładuję się w 100%, jeżeli go nie będzie to załaduje). Na pewno da się jakoś zatrzymać przynajmniej EventListenera :/ i wtedy z górki. Tak czy siak, powodzenia!

Edit: Albo coś w rodzaju, aby eventListener się nie połapał i nie zdążył :P (bo chyba działa z deley'em, prawda?)

for( ; ; ) {                 
      document.hasFocus = () => true;
   }
//może też być: while(1<2) :zamiast: for( ; ; )

**Comment by skhyr** [comment]
@Xonn1com testportal nadpisanie hasFocus na document wykrywa jako nielegalną wtyczkę, więc nie można korzystać z tego sposobu. Da się natomiast usuwać event listenera ale to nic nie daje bo co chwile go dodają więc jeśli usunę i nawet będę to robił 2 razy częściej niż oni dodają to pojawi się mała przerwa w której on będzie. Jedynym sposobem jest edytowanie ich skryptów na stronie ale tego już nie umiem choć pewnie jest robialne bo to wszystko po stronie klienta

**Comment by skhyr** [comment]
Działa znów
