### ISSUE TITLE
Testportal blokuje rozwiązywanie testu z tą wtyczką

### ISSUE THREAD

**Issue by Juby210** [skhyr/anihilator#5]
![image](https://user-images.githubusercontent.com/31005896/83513677-833b2400-a4d2-11ea-901c-6a15f003b53a.png)

Przeglądarka: chromium 85.0.4163.0

**Comment by fhodun** [comment]
Sprawdziłem i wychodzi na to że testportal blokuje to konkretne rozszerzenie<s>, lecz gdy próbuję z rozszerzeniem z kompletnie innym manifestem też nie działa</s> :(

**Comment by diel0** [comment]
Przy użyciu anihilatora:
![obraz](https://user-images.githubusercontent.com/55411451/83520847-a4a20d00-a4de-11ea-85ac-7cf2a635377c.png)
To samo z innym manifestem nie działa, lecz testportal go nie blokuje:
![obraz](https://user-images.githubusercontent.com/55411451/83520981-d9ae5f80-a4de-11ea-99e4-7f423d4e6ce3.png)

**Comment by fhodun** [comment]
Ta przerobiona wersja tego rozszerzenia nie jest blokowana - https://github.com/diel0/itakniezdasz
ale i tak nie działa

**Comment by skhyr** [comment]
@diel0  jak używasz mojego kodu tylko chcesz coś zmienić to robi się forka obczaj sobie takie rzeczy bo nie wypada tak kraść. Testportal teraz blokuje tj wykrywa jako wtyczkę jeśli nadpisze się hasFocus elemnetu document. Można usunąć po prostu EventListenera na focus blur itd ale ich kod co chwilę go dodaje

**Comment by skhyr** [comment]
Jeśli ktoś ma pomysł to zapraszam do forkowania i pull requestowania

**Comment by fhodun** [comment]
Sory, dopiero zaczynam z GitHubem i o tym nie wiedziałem. Zaraz ogarnę

**Comment by morsisko** [comment]
Dodałem pull requesta który zapobiega wykryciu nadpisania tej metody. #6

**Comment by skhyr** [comment]
śmiga, brawo!
