### ISSUE TITLE
młokosie

### ISSUE THREAD

**Issue by ppmaks** [skhyr/anihilator#7]
a gdze porgame d3ebilu niie ma .js przez cb zmarnowalem 10 minut mojego rzyciia

**Comment by Juby210** [comment]
kod masz na branchu `chrome`

**Comment by skhyr** [comment]
@ppmaks no cringe zapostowałeś wszystko opisane jest jak widać @Juby210 ogarnął a ty nie powiedziałbym coś ale już nie powiem tyle w temacie zamykam.
